{% set name = "dependente" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dependente-{{ version }}.tar.gz
  sha256: 463f18c148bd87a9677414f5b2a0256dbdf992ec4db480dd5f0879c7182d5305

build:
  number: 0
  noarch: python
  entry_points:
    - dependente = dependente.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=6.2
  run:
    - python >=3.6
    - click <9.0.0,>=8.0.0
    - tomli <3.0.0,>=1.1.0

test:
  imports:
    - dependente
  commands:
    - pip check
    - dependente -h
  requires:
    - pip

about:
  home: https://github.com/fatiando/dependente
  summary: Inspect Python package dependencies
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
