{% set name = "dependente" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dependente-{{ version }}.tar.gz
  sha256: 3478cd56ece9b9afbe33c4da132e65305ea0ef474b1a906b2d6d79c934cc2452

build:
  number: 1
  noarch: python
  entry_points:
    - dependente = dependente.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - click <9.0.0,>=8.0.0
    - tomli <3.0.0,>=1.1.0

test:
  imports:
    - dependente
  commands:
    - pip check
    - dependente -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fatiando/dependente
  summary: Inspect Python package dependencies
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
